name: Nightly Build

on:
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: andronics/base

jobs:
  
  build-and-release:
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: container registry login
        uses: docker/login-action@1f401f745bf57e30b3a2800ad308a87d2ebdf14b
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: metadata extraction
        id: meta
        uses: docker/metadata-action@35e9aff4f5d665b5aa8a8f2adffaf8a1b5f49cc0
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD' tz='Europe/London'}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: commit count
        run: echo "COMMIT_COUNT=$(git log --oneline --since '24 hours ago' | wc -l)" >> "$GITHUB_ENV"
      
      - name: build and push
        uses: docker/build-push-action@4fad532b9fdbfb80f436784834374a1c11834153
        if: ${{ env.COMMIT_COUNT > 0 }}
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: clean
        if: always() && github.event_name != 'pull_request'
        run: |
          rm -f ${HOME}/.docker/config.json